version: '3'
services:
  php_app:
    build:
      context: .
      dockerfile: php.Dockerfile
    env_file: .env
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - app_db

  app_db:
    image: mariadb:11.2
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3310:3306"
  
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: app_db
    ports:
      - "8085:80"
    depends_on:
      - app_db